extend type Query {
  """
  ✨ Look up a single `LeaderboardEntry` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  leaderboardEntry(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: LeaderboardEntry_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LeaderboardEntry_FirstRow
  ): LeaderboardEntry @fdc_generated(from: "LeaderboardEntry", purpose: QUERY_SINGLE)
  """
  ✨ List `LeaderboardEntry` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  leaderboardEntries(
    """
    Filter condition to narrow down the query results.
    """
    where: LeaderboardEntry_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LeaderboardEntry_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LeaderboardEntry_Having
  ): [LeaderboardEntry!]! @fdc_generated(from: "LeaderboardEntry", purpose: QUERY_MULTIPLE)
}
